name: Receive Pull_request
on:
  pull_request_target:
    branches-ignore:
      - "gh-pages*"
    tags-ignore: 
      - "**"
jobs:
  approve: # to approve a workflow run(through github environment)
    runs-on: ubuntu-latest
    steps:
    - name: Approve
      run: echo For security reasons, all pull requests need to be approved first before running any automated CI.
  test:
    name: Test Job
    runs-on: ubuntu-latest
    needs: [approve]
    environment:
      name: pr-reviews
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ secrets.PYTHON_MIN_VERSION }} # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip -V
          pip install --upgrade -e .
      - name: Validate & Coverage Report
        run: |
          "./scripts/black.sh"
          "./scripts/coverage.sh"