name: Release
on:
  push:
    branches-ignore:
      - "gh-pages*"
    tags-ignore: 
      - "**"
  pull_request:
    branches-ignore:
      - "gh-pages*"
    tags-ignore: 
      - "**"
jobs:
  test:
    name: Test Job
    # Support [skip ci] out of box with github actions Workaround
    # Only works for push https://github.com/actions/runner/issues/774
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && contains(toJson(github.event.commits), '[skip ci]') == false)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        env:
          PYTHON_MIN_VERSION: ${{ secrets.PYTHON_MIN_VERSION }}
        with:
          python-version: env.PYTHON_MIN_VERSION # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip -V
          pip install --upgrade -e .
      - name: Validate & Coverage Report
        run: |
          "./scripts/black.sh"
          "./scripts/coverage.sh"
        # TODO add more lines here to be executed in the test stage e.g. pyinstaller etc.
  generate-linux-bin:
    name: Generate Linux bin
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ secrets.PYTHON_MIN_VERSION }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip -V
          pip install --upgrade -e .
      - name: Run Pyinstaller
        run: |
          "./scripts/linux-pyinstaller.sh"
        # upload linux-binary
      - name: Upload linux-binary
        uses: actions/upload-artifact@v2
        with:
          name: linux-binary
          path: linux-binary-latest.zip
          retention-days: 1
  generate-macos-bin:
    name: Generate MacOS bin
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: macos-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ secrets.PYTHON_MIN_VERSION }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip -V
          pip install --upgrade -e .
      - name: Run Pyinstaller
        run: |
          "./scripts/macos-pyinstaller.sh"
        # upload macos-binary 
      - name: Upload macos-binary
        uses: actions/upload-artifact@v2
        with:
          name: macos-binary
          path: macos-binary-latest.zip
          retention-days: 1
  generate-win-bin:
    name: Generate Win bin
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ secrets.PYTHON_MIN_VERSION }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip -V
          pip install --upgrade -e .
      - name: Run Pyinstaller
        run: |
          & "./scripts/win-pyinstaller.ps1"
        # upload win-binary
      - name: Upload win-binary
        uses: actions/upload-artifact@v2
        with:
          name: win-binary
          path: win-binary-latest.zip
          retention-days: 1
  release:
    name: Release Job
    runs-on: ubuntu-latest
    needs:
      - test
      - generate-linux-bin
      - generate-macos-bin
      - generate-win-bin
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ secrets.PYTHON_MIN_VERSION }}
      - name: Install dependencies
        run: |
          pip install --upgrade pip testresources setuptools wheel
          pip -V
          pip install --upgrade -e .
      - name: Setup NodeJS LTS
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: |
          npm prune && npm i
          gulp validate
      # download all our binary files
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: npx semantic-release
